# Generated by Django 6.1 on 2026-08-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Private details only you can see — use this to verify claims (e.g. serial number, exact contents).'),
        ),
    ]
