# Generated by Django 6.1 on 2026-08-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_item_private_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='handoff_details',
            field=models.TextField(blank=True, help_text='Contact info / instructions the finder provides upon approval (phone, meeting spot, etc.)'),
        ),
    ]
